name: chatbot_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  google_sign_in: ^7.2.0
  url_launcher: ^6.3.2

  cupertino_icons: ^1.0.8
  http: ^1.6.0
  firebase_core: ^4.13.0
  firebase_auth: ^6.5.7
  cloud_firestore: ^6.8.0
  firebase_messaging: ^16.5.0
  flutter_local_notifications: ^22.3.0
  image_picker: ^1.2.1
  emoji_picker_flutter: ^4.3.0
  record: ^7.1.1
  just_audio: ^0.10.6
  path_provider: ^2.1.6
  file_picker: ^12.2.0
  flutter_webrtc: ^1.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/chats_header.png
    - assets/images/profile/profile1.jpg
    - assets/images/profile/profile2.jpg
    - assets/images/profile/profile3.png
    - assets/images/profile/profile4.png
    - assets/images/profile/profile5.png
    - assets/images/profile/profile6.png
    - assets/images/profile/profile7.png
    - assets/images/profile/profile8.png
    - assets/images/profile/profile9.png
    - assets/images/profile/profile10.png
    - assets/audio/call_incoming_ringtone.mp3
    - assets/audio/call_outgoing_ringback.mp3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/nexus_logo.png"
  min_sdk_android: 21