// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this Platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXHrQsfvO_D37HuEweJsEyzB59tOk8USg',
    appId: '1:639346299672:web:1b6adebe3dc335fbb6c46d',
    messagingSenderId: '639346299672',
    projectId: 'chatbot-1973a',
    authDomain: 'chatbot-1973a.firebaseapp.com',
    storageBucket: 'chatbot-1973a.firebasestorage.app',
    measurementId: 'G-G2VDRP7HXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdzrMCEHBm52MmkzxWKi53aLObH8JcTG4',
    appId: '1:639346299672:android:576512308708f8c1b6c46d',
    messagingSenderId: '639346299672',
    projectId: 'chatbot-1973a',
    storageBucket: 'chatbot-1973a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWjMaSlIGacAB_aNbfctwYRvPFlp8KN_I',
    appId: '1:639346299672:ios:91f65b20594db880b6c46d',
    messagingSenderId: '639346299672',
    projectId: 'chatbot-1973a',
    storageBucket: 'chatbot-1973a.firebasestorage.app',
    iosBundleId: 'com.example.chatbotApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWjMaSlIGacAB_aNbfctwYRvPFlp8KN_I',
    appId: '1:639346299672:ios:91f65b20594db880b6c46d',
    messagingSenderId: '639346299672',
    projectId: 'chatbot-1973a',
    storageBucket: 'chatbot-1973a.firebasestorage.app',
    iosBundleId: 'com.example.chatbotApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXHrQsfvO_D37HuEweJsEyzB59tOk8USg',
    appId: '1:639346299672:web:e37bd63842465c54b6c46d',
    messagingSenderId: '639346299672',
    projectId: 'chatbot-1973a',
    authDomain: 'chatbot-1973a.firebaseapp.com',
    storageBucket: 'chatbot-1973a.firebasestorage.app',
    measurementId: 'G-CSTGQC1967',
  );
}
