import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../services/club_poll_service.dart';

class ClubPollsPage extends StatefulWidget { final String clubDocId; final bool canCreate; const ClubPollsPage({super.key, required this.clubDocId, required this.canCreate}); @override State<ClubPollsPage> createState()=>_ClubPollsPageState(); }
class _ClubPollsPageState extends State<ClubPollsPage> {
  final uid=FirebaseAuth.instance.currentUser?.uid ?? '';
  Future<void> _create() async { final q=TextEditingController(); final opts=[TextEditingController(),TextEditingController()]; await showModalBottomSheet(context:context,isScrollControlled:true,backgroundColor:const Color(0xFF1B120A),builder:(c)=>Padding(padding:EdgeInsets.only(left:20,right:20,top:20,bottom:MediaQuery.of(c).viewInsets.bottom+20),child:StatefulBuilder(builder:(c,set)=>Column(mainAxisSize:MainAxisSize.min,children:[const Text('Create Poll',style:TextStyle(color:Colors.white,fontSize:20,fontWeight:FontWeight.bold)),TextField(controller:q,style:const TextStyle(color:Colors.white),decoration:const InputDecoration(labelText:'Question',labelStyle:TextStyle(color:Colors.white54))),...opts.asMap().entries.map((e)=>TextField(controller:e.value,style:const TextStyle(color:Colors.white),decoration:InputDecoration(labelText:'Option ${e.key+1}',labelStyle:const TextStyle(color:Colors.white54)))),Row(children:[TextButton(onPressed:(){set((){opts.add(TextEditingController());});},child:const Text('Add option')),const Spacer(),ElevatedButton(onPressed:()async{try{await ClubPollService.createPoll(clubId:widget.clubDocId,uid:uid,question:q.text,options:opts.map((e)=>e.text).toList());if(c.mounted)Navigator.pop(c);}catch(e){ScaffoldMessenger.of(c).showSnackBar(SnackBar(content:Text(e.toString().replaceFirst('Exception: ',''))));}},child:const Text('Create'))])])))); }
  @override Widget build(BuildContext context)=>Scaffold(backgroundColor:Colors.transparent,floatingActionButton:widget.canCreate?FloatingActionButton(onPressed:_create,child:const Icon(Icons.add)):null,body:StreamBuilder<QuerySnapshot<Map<String,dynamic>>>(stream:ClubPollService.watchPolls(widget.clubDocId),builder:(c,s){if(s.hasError)return Center(child:Text('Unable to load polls',style:TextStyle(color:Colors.white70)));if(!s.hasData)return const Center(child:CircularProgressIndicator());final docs=s.data!.docs;if(docs.isEmpty)return const Center(child:Text('No polls yet.',style:TextStyle(color:Colors.white54)));return ListView.builder(padding:const EdgeInsets.all(16),itemCount:docs.length,itemBuilder:(c,i)=>_PollCard(clubId:widget.clubDocId,doc:docs[i],uid:uid));}));
}
class _PollCard extends StatelessWidget { final String clubId; final QueryDocumentSnapshot<Map<String,dynamic>> doc; final String uid; const _PollCard({required this.clubId,required this.doc,required this.uid}); @override Widget build(BuildContext context){final d=doc.data();final options=(d['options'] as List? ?? const []).map((e)=>Map<String,dynamic>.from(e as Map)).toList();final voters=List<String>.from(d['voters']??const[]);final voted=voters.contains(uid);final total=(d['totalVotes'] as num?)?.toInt()??0;return Card(color:const Color(0xFF1B120A),child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(d['question']??'',style:const TextStyle(color:Colors.white,fontSize:17,fontWeight:FontWeight.bold)),const SizedBox(height:10),...options.asMap().entries.map((e){final votes=(e.value['votes'] as num?)?.toInt()??0;final pct=total==0?0.0:votes/total;return InkWell(onTap:voted||d['closed']==true?null:()=>ClubPollService.vote(clubId:clubId,pollId:doc.id,uid:uid,optionIndex:e.key),child:Padding(padding:const EdgeInsets.symmetric(vertical:7),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(e.value['text']??'',style:const TextStyle(color:Colors.white70)),if(voted||d['closed']==true)LinearProgressIndicator(value:pct,minHeight:7),if(voted||d['closed']==true)Text('${(pct*100).round()}%  •  $votes votes',style:const TextStyle(color:Colors.white38,fontSize:11))])));}),const SizedBox(height:6),Text('$total total votes${d['closed']==true?' • Ended':voted?' • You voted':' • Active'}',style:const TextStyle(color:Colors.white38,fontSize:12))])));}}
